2022-05-11 14:42:59,532 - integer out of range
Traceback (most recent call last):
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\connect_sql.py", line 154, in <module>
    cur.execute(f'INSERT INTO nf_entrada_itens (natureza_operacao, serie, cnpj_cpf_destinatario)'
psycopg2.errors.NumericValueOutOfRange: integer out of range

