2022-07-25 18:46:44,355 - [WinError 3] The system cannot find the path specified: 'C:\\Users\\allan.mesquita\\OneDrive - NTT\\Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\Testes\\01 Processamento\\TERCA VIX 202207182008 32220704626426000700550010000492721684973626_Recebimento.xlsx' -> 'C:\\Users\\allan.mesquita\\OneDrive - NTT\\Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\Testes\\03 Erros\\TERCA VIX 202207182008 32220704626426000700550010000492721684973626_Recebimento.xlsx'
Traceback (most recent call last):
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_Zone\main_qualidade2.py", line 132, in <module>
    os.replace(path + file_name, "C:\\Users\\allan.mesquita\\OneDrive - NTT\\Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\Testes\\03 Erros\\" + file_name)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\allan.mesquita\\OneDrive - NTT\\Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\Testes\\01 Processamento\\TERCA VIX 202207182008 32220704626426000700550010000492721684973626_Recebimento.xlsx' -> 'C:\\Users\\allan.mesquita\\OneDrive - NTT\\Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\Testes\\03 Erros\\TERCA VIX 202207182008 32220704626426000700550010000492721684973626_Recebimento.xlsx'
