2022-05-30 17:49:29,700 - No module named 'class_erros'
Traceback (most recent call last):
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_Zone\main_qualidade2.py", line 127, in <module>
    resultado = validacao.exp_validacao(aba, qtd_linhas)
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_Zone\Modulos\validacao.py", line 283, in exp_validacao
    from class_erros import Error
ModuleNotFoundError: No module named 'class_erros'
